name: 'Run Bazel'
description: 'Downloads bazel using bazelisk and then executes an action using it'
inputs:
  command:
    description: 'The command to run using bazel'
    required: true
  bazelisk-version:
    description: 'The version of bazelisk to use'
    default: 1.3.0
runs:
  using: 'node12'
  main: 'dist/index.js'
